name: ganglife
version: '${version}'
main: de.marc.ganglife.Main.main
api-version: '1.20'

commands:
  giveitem:
  gamemode:
    aliases: [gm]
  navigation:
    aliases: [navi]
  werbung:
    aliases: [ad]
  aduty:
  build:
  blockfarming:
  broadcast:
    aliases: [bc]
  clear:
  registeratm:
  heal:
  dropgun:
  pay:
  durchsuchen:
  ffastats:
  profil:
  fraklager:
    aliases: [flager]
  uncuff:
  teleport:
  tphere:
  vanish:
  verify:
  arevive:
  showgehalt: